// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqoe-BoJMwwvnAPwDUiMYQLGnu22J2pqM',
    appId: '1:462781735560:web:9e55b374ed7abe0431f53d',
    messagingSenderId: '462781735560',
    projectId: 'uphil-9fc91',
    authDomain: 'uphil-9fc91.firebaseapp.com',
    storageBucket: 'uphil-9fc91.firebasestorage.app',
    measurementId: 'G-2NG4DL1Z8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsa2tNcgw3x4LOyVbwfH5AvwbmJ7dorFU',
    appId: '1:462781735560:android:4e6e435e6ec423d931f53d',
    messagingSenderId: '462781735560',
    projectId: 'uphil-9fc91',
    storageBucket: 'uphil-9fc91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABrAm-HbktgOP08MSR6Pv-3fvXphWbz2I',
    appId: '1:462781735560:ios:6ed99dcbb9e1d57331f53d',
    messagingSenderId: '462781735560',
    projectId: 'uphil-9fc91',
    storageBucket: 'uphil-9fc91.firebasestorage.app',
    iosBundleId: 'com.example.uphill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABrAm-HbktgOP08MSR6Pv-3fvXphWbz2I',
    appId: '1:462781735560:ios:6ed99dcbb9e1d57331f53d',
    messagingSenderId: '462781735560',
    projectId: 'uphil-9fc91',
    storageBucket: 'uphil-9fc91.firebasestorage.app',
    iosBundleId: 'com.example.uphill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqoe-BoJMwwvnAPwDUiMYQLGnu22J2pqM',
    appId: '1:462781735560:web:f29688112df5fa0331f53d',
    messagingSenderId: '462781735560',
    projectId: 'uphil-9fc91',
    authDomain: 'uphil-9fc91.firebaseapp.com',
    storageBucket: 'uphil-9fc91.firebasestorage.app',
    measurementId: 'G-JRJL8CYQMV',
  );
}
